title: Samiur Khan
email: samiurkh1n@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
        Samiur's personal home page.
baseurl: ""
url: ""
permalink: /posts/:year/:month/:day/:title/
twitter_username: samiurkh1n
github_username:  samiurkh1n

# Build settings
markdown: kramdown
theme: clean-jekyll-theme
plugins:
  - jekyll-feed

exclude:
   - Gemfile
   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
